"""Bilingual UI strings (Spanish default, English optional).

Qt-free on purpose: no build tooling, no extra files in the packaged
executable, and a completeness test can prove that neither language has
holes. Engine diagnostics (extractor/CLI errors) intentionally stay in
Spanish as stable log vocabulary.
"""

from __future__ import annotations

SUPPORTED_LANGUAGES = ("es", "en")

_current = "es"


def set_language(lang: str) -> str:
    global _current
    _current = lang if lang in SUPPORTED_LANGUAGES else "es"
    return _current


def get_language() -> str:
    return _current


def tr(key: str, **kwargs: object) -> str:
    template = STRINGS.get(_current, {}).get(key)
    if template is None:
        template = STRINGS["es"].get(key, key)
    if kwargs:
        return template.format(**kwargs)
    return template


STRINGS: dict = {
    "es": {
        "app.title": "Consolidador de Textos",
        "menu.file": "&Archivo",
        "menu.tools": "&Herramientas",
        "menu.view": "&Ver",
        "menu.help": "A&yuda",
        "menu.language": "Idioma",
        "act.add_files": "Agregar archivos...",
        "act.add_folder": "Agregar carpeta...",
        "act.save": "Guardar consolidado...",
        "act.save_recipe": "Guardar receta...",
        "act.load_recipe": "Cargar receta...",
        "act.export_log": "Exportar informe de errores...",
        "act.exit": "Salir",
        "act.review_duplicates": "Revisar duplicados...",
        "act.dark": "Modo oscuro",
        "act.about": "Acerca de",
        "files.title": "Archivos de la sesión",
        "files.tooltip": "Arrastra para reordenar",
        "btn.remove": "Quitar",
        "btn.clear": "Limpiar",
        "tip.remove": "Eliminar archivos seleccionados de la sesión",
        "tip.clear": "Limpiar la sesión actual",
        "tip.up": "Subir el archivo seleccionado",
        "tip.down": "Bajar el archivo seleccionado",
        "name.up": "Subir",
        "name.down": "Bajar",
        "a11y.progress": "Progreso de la extracción en curso",
        "check.recursive": "Incluir subcarpetas",
        "tip.recent": "Selecciona una carpeta reciente para volver a procesarla",
        "recent.placeholder": "Carpetas recientes...",
        "settings.title": "Configuración de consolidación",
        "sep.title": "Separador entre archivos",
        "sep.blank": "Línea en blanco simple",
        "sep.dashes": "Línea de guiones (---)",
        "sep.filename": "Nombre del archivo como encabezado",
        "sep.custom": "Separador personalizado",
        "custom.placeholder": "Usa \\n para salto de línea y {filename} para el siguiente archivo",
        "custom.tooltip": "Texto literal entre archivos. Soporta \\n, \\t y {filename}.",
        "output.label": "Formato de salida",
        "preview.label": "Vista previa ({count} archivos, {chars} caracteres)",
        "preview.tooltip": "Contenido exacto que se guardará",
        "status.ready": "Listo",
        "status.processing": "Procesando archivos...",
        "status.progress": "Procesando {current}/{total}: {name}",
        "status.nothing_new": "No se agregaron archivos nuevos (duplicados o vacíos).",
        "status.done_errors": "Completado con {count} omitidos.",
        "status.done_ok": "Completado: {count} archivos procesados.",
        "status.select_remove": "Selecciona uno o más archivos para quitar.",
        "status.removed": "Archivos quitados de la sesión.",
        "status.cleared": "Sesión limpia.",
        "status.restored": "Sesión restaurada: {ok} archivos ({missing} ya no existen).",
        "dlg.select_files": "Seleccionar archivos",
        "dlg.select_folder": "Seleccionar carpeta",
        "dlg.save": "Guardar consolidado",
        "dlg.save_recipe": "Guardar receta",
        "dlg.load_recipe": "Cargar receta",
        "dlg.export_log": "Exportar informe de errores",
        "filter.supported": "Archivos soportados ({exts})",
        "filter.all": "Todos los archivos (*)",
        "filter.yaml": "Receta YAML (*.yaml *.yml)",
        "filter.txt": "Texto plano (*.txt)",
        "filter.docx": "Documento Word (*.docx)",
        "filter.log": "Registro (*.log);;Texto (*.txt)",
        "default.recipe_name": "receta.yaml",
        "default.output_txt": "consolidado.txt",
        "default.output_docx": "consolidado.docx",
        "default.log_name": "errores_consolidacion.log",
        "log.suffix": "_errores",
        "recipe.output_suffix": "_consolidado",
        "folder.title": "Carpeta",
        "folder.empty": "No se encontraron archivos soportados en la carpeta seleccionada.",
        "folder.read_error": "No se pudo leer la carpeta:\n{detail}",
        "recent.title": "Carpeta reciente",
        "recent.gone": "La carpeta ya no existe.",
        "processing.title": "Procesando",
        "processing.busy": "Espera a que termine el proceso actual.",
        "errors.title": "Archivos omitidos",
        "errors.body": "Se procesaron {ok} archivos correctamente.\n{errors} archivos se omitieron.\n\n¿Quieres ver el informe?",
        "clear.title": "Limpiar sesión",
        "clear.body": "¿Quitar todos los archivos y errores de la sesión actual?",
        "dupes.need_two": "Agrega al menos dos archivos para buscar duplicados.",
        "dupes.no_change": "Sin cambios: no se quitó ningún duplicado.",
        "dupes.removed": "Se quitaron {count} archivos duplicados de la sesión.",
        "restore.missing_error": "El archivo ya no existe.",
        "save.empty": "No hay archivos en la sesión para consolidar.",
        "save.done": "Archivo guardado en:\n{path}",
        "save.done_log": "\n\nInforme de errores guardado en:\n{path}",
        "save.failed": "No se pudo guardar el archivo:\n{detail}",
        "recipe.empty": "No hay archivos en la sesión para guardar como receta.",
        "recipe.save_failed": "No se pudo guardar la receta:\n{detail}",
        "recipe.saved": "Receta guardada en:\n{recipe}\n\nSalida prevista:\n{output}",
        "recipe.load_failed": "No se pudo cargar la receta:\n{detail}",
        "recipe.ignored": "Esta receta usa funciones que la interfaz gráfica no aplica.\nSe cargarán solo los archivos y el separador:\n\n- {items}",
        "recipe.ignored.transforms": "transformaciones: {items}",
        "recipe.ignored.dedup": "deduplicación: {mode}",
        "recipe.ignored.ocr": "OCR: {name}",
        "recipe.ignored.formats": "formatos de salida: {items}",
        "report.title": "Informe de archivos omitidos",
        "report.header": "Informe de archivos omitidos",
        "report.date": "Fecha: {date}",
        "report.total": "Total omitidos: {count}",
        "report.file": "Archivo: {path}",
        "report.reason": "Motivo: {reason}",
        "log.title": "Informe",
        "log.empty": "No hay archivos omitidos en la sesión actual.",
        "log.saved": "Informe guardado en:\n{path}",
        "log.save_failed": "No se pudo guardar el informe:\n{detail}",
        "about.body": "Consolidador de Textos\nHerramienta open source para consolidar texto de múltiples archivos.\n\nLicencia MIT.\nDependencias: PySide6, python-docx, pypdf.",
        "dupes.dlg_title": "Revisar duplicados",
        "dupes.none_found": "No se encontraron duplicados exactos ni similares (umbral 90%).",
        "dupes.exact_group": "Idénticos: {names}",
        "dupes.keep_first_check": "Eliminar duplicados (conservar {name})",
        "dupes.pair_title": "{a} <> {b} — similitud {pct}",
        "dupes.keep_both": "Conservar ambos",
        "dupes.keep_name": "Conservar {name}",
        "dupes.apply": "Aplicar",
        "dupes.cancel": "Cancelar",
    },
    "en": {
        "app.title": "Text Consolidator",
        "menu.file": "&File",
        "menu.tools": "&Tools",
        "menu.view": "&View",
        "menu.help": "&Help",
        "menu.language": "Language",
        "act.add_files": "Add files...",
        "act.add_folder": "Add folder...",
        "act.save": "Save consolidated...",
        "act.save_recipe": "Save recipe...",
        "act.load_recipe": "Load recipe...",
        "act.export_log": "Export error report...",
        "act.exit": "Exit",
        "act.review_duplicates": "Review duplicates...",
        "act.dark": "Dark mode",
        "act.about": "About",
        "files.title": "Session files",
        "files.tooltip": "Drag to reorder",
        "btn.remove": "Remove",
        "btn.clear": "Clear",
        "tip.remove": "Remove selected files from the session",
        "tip.clear": "Clear the current session",
        "tip.up": "Move the selected file up",
        "tip.down": "Move the selected file down",
        "name.up": "Move up",
        "name.down": "Move down",
        "a11y.progress": "Ongoing extraction progress",
        "check.recursive": "Include subfolders",
        "tip.recent": "Pick a recent folder to process it again",
        "recent.placeholder": "Recent folders...",
        "settings.title": "Consolidation settings",
        "sep.title": "Separator between files",
        "sep.blank": "Single blank line",
        "sep.dashes": "Dash line (---)",
        "sep.filename": "File name as header",
        "sep.custom": "Custom separator",
        "custom.placeholder": "Use \\n for line breaks and {filename} for the next file",
        "custom.tooltip": "Literal text between files. Supports \\n, \\t and {filename}.",
        "output.label": "Output format",
        "preview.label": "Preview ({count} files, {chars} characters)",
        "preview.tooltip": "Exact content that will be saved",
        "status.ready": "Ready",
        "status.processing": "Processing files...",
        "status.progress": "Processing {current}/{total}: {name}",
        "status.nothing_new": "No new files added (duplicates or empty).",
        "status.done_errors": "Completed with {count} skipped.",
        "status.done_ok": "Completed: {count} files processed.",
        "status.select_remove": "Select one or more files to remove.",
        "status.removed": "Files removed from the session.",
        "status.cleared": "Session cleared.",
        "status.restored": "Session restored: {ok} files ({missing} no longer exist).",
        "dlg.select_files": "Select files",
        "dlg.select_folder": "Select folder",
        "dlg.save": "Save consolidated output",
        "dlg.save_recipe": "Save recipe",
        "dlg.load_recipe": "Load recipe",
        "dlg.export_log": "Export error report",
        "filter.supported": "Supported files ({exts})",
        "filter.all": "All files (*)",
        "filter.yaml": "YAML recipe (*.yaml *.yml)",
        "filter.txt": "Plain text (*.txt)",
        "filter.docx": "Word document (*.docx)",
        "filter.log": "Log (*.log);;Text (*.txt)",
        "default.recipe_name": "recipe.yaml",
        "default.output_txt": "consolidated.txt",
        "default.output_docx": "consolidated.docx",
        "default.log_name": "consolidation_errors.log",
        "log.suffix": "_errors",
        "recipe.output_suffix": "_consolidated",
        "folder.title": "Folder",
        "folder.empty": "No supported files found in the selected folder.",
        "folder.read_error": "Could not read the folder:\n{detail}",
        "recent.title": "Recent folder",
        "recent.gone": "The folder no longer exists.",
        "processing.title": "Processing",
        "processing.busy": "Wait for the current process to finish.",
        "errors.title": "Skipped files",
        "errors.body": "Processed {ok} files successfully.\n{errors} files were skipped.\n\nView the report?",
        "clear.title": "Clear session",
        "clear.body": "Remove all files and errors from the current session?",
        "dupes.need_two": "Add at least two files to look for duplicates.",
        "dupes.no_change": "No changes: no duplicates removed.",
        "dupes.removed": "Removed {count} duplicate files from the session.",
        "restore.missing_error": "The file no longer exists.",
        "save.empty": "No files in the session to consolidate.",
        "save.done": "File saved to:\n{path}",
        "save.done_log": "\n\nError report saved to:\n{path}",
        "save.failed": "Could not save the file:\n{detail}",
        "recipe.empty": "No files in the session to save as a recipe.",
        "recipe.save_failed": "Could not save the recipe:\n{detail}",
        "recipe.saved": "Recipe saved to:\n{recipe}\n\nPlanned output:\n{output}",
        "recipe.load_failed": "Could not load the recipe:\n{detail}",
        "recipe.ignored": "This recipe uses features the desktop UI does not apply.\nOnly files and the separator will be loaded:\n\n- {items}",
        "recipe.ignored.transforms": "transforms: {items}",
        "recipe.ignored.dedup": "deduplication: {mode}",
        "recipe.ignored.ocr": "OCR: {name}",
        "recipe.ignored.formats": "output formats: {items}",
        "report.title": "Skipped files report",
        "report.header": "Skipped files report",
        "report.date": "Date: {date}",
        "report.total": "Total skipped: {count}",
        "report.file": "File: {path}",
        "report.reason": "Reason: {reason}",
        "log.title": "Report",
        "log.empty": "No skipped files in the current session.",
        "log.saved": "Report saved to:\n{path}",
        "log.save_failed": "Could not save the report:\n{detail}",
        "about.body": "Text Consolidator\nOpen source tool to consolidate text from multiple files.\n\nMIT License.\nDependencies: PySide6, python-docx, pypdf.",
        "dupes.dlg_title": "Review duplicates",
        "dupes.none_found": "No exact or similar duplicates found (90% threshold).",
        "dupes.exact_group": "Identical: {names}",
        "dupes.keep_first_check": "Remove duplicates (keep {name})",
        "dupes.pair_title": "{a} <> {b} — {pct} similar",
        "dupes.keep_both": "Keep both",
        "dupes.keep_name": "Keep {name}",
        "dupes.apply": "Apply",
        "dupes.cancel": "Cancel",
    },
}
